# Generated by Django 5.0.4 on 2024-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trabajos", "0002_porfolioitem_github_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="porfolioitem",
            name="github_link_img",
            field=models.ImageField(upload_to="../static/i"),
        ),
        migrations.AlterField(
            model_name="porfolioitem",
            name="image",
            field=models.ImageField(upload_to="../static/i"),
        ),
    ]
