# Generated by Django 5.0.4 on 2024-04-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trabajos", "0005_newproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("sitio_web", models.URLField()),
                ("logo", models.ImageField(upload_to="../static/i")),
            ],
        ),
    ]
